### ISSUE TITLE
Improvement: Engine API http and ws on the same port

### ISSUE THREAD

**Issue by yorickdowne** [status-im/nimbus-eth1#1347]
For easier configuration and to match every other EL out there, it'd be very helpful if http and ws for the Engine API were on the same port `8551` by default, instead of on `8550` and `8551` respectively.

WS is an upgrade from HTTP after the initial connection.

```
    --engine-api              Enable the Engine API [=false].
     --engine-api-port         Listening port for the Engine API [=8550].
     --engine-api-address      Listening address for the Engine API [=127.0.0.1,
                               meaning local host only].
     --engine-api-ws           Enable the WebSocket Engine API [=false].
     --engine-api-ws-port      Listening port for the WebSocket Engine API
                               [=8551].
     --engine-api-ws-address   Listening address for the WebSocket Engine API
                               [=127.0.0.1, meaning local host only].
```

**Comment by jangko** [comment]
TODO: 
- devise a common HHTP server than can be used by JSON RPC, Graphql, and websocket services.
- both engine api and ws services need to use common HTTP server instead of it's own HTTP server. 
- detect HTTP upgrade and route the request to ws
- can GET/POST path contains `/graphql` and route the request to graphql
- request maybe JSON RPC if the `ContentType` contains `application/json`.

**Comment by jangko** [comment]
related issues:
- status-im/nim-graphql#113
- status-im/nim-json-rpc#174
- status-im/nim-websock#133
