### ISSUE TITLE
Nimbus t8n forkname+xxxx eip support

### ISSUE THREAD

**Issue by winsvega** [status-im/nimbus-eth1#1607]
Has Nimbus implemented eip1153? 
Sometimes before the inclusion we use this schema  Shanghai+1153 to tell that 1153 is to be activated on top of Shanghai rules. 
This is because we don't know if 1153 is gonna be in Merge or Shanghai or Cancun 
so the t8n allows to generate the tests for 1153 using the latest evm revision (Shanghai for instance) 
And then when it is included we just rename it to Shanghai. 
This is not possible for all eips but some.

**Comment by jangko** [comment]
We have an open PR #1401 exploring this possibility, but then I realize something that is very difficult to solve. Nimbus EVM opcode dispatcher is generated during compiletime, not at runtime. And the instruction table is generated for every hard fork. Runtime modification to this table is very difficult, because the static table need to be converted into a dynamic table, and the optimized codegen(to C) will dissapear.
Another hindrance is nimbus support for evmc, evmc API act as a barrier to this runtime EIP configuration. 
If by any chance we can make 1401 to works, it probably only works for pure nim EVM, not the evmc.

**Comment by winsvega** [comment]
This feauture is not mandatory.
Whats important is to be able to have access to the evm as soon as eip is implemented

**Comment by jangko** [comment]
Due to technical reason, this feature will not be implemented in nimbus-eth1.
