### ISSUE TITLE
Add eth_getProof JSON-RPC implementation

### ISSUE THREAD

**Issue by kdeme** [status-im/nimbus-eth1#1944]
See https://eips.ethereum.org/EIPS/eip-1186

Geth implementation: https://github.com/ethereum/go-ethereum/blob/81fd1b3cf9c4c4c9f0e06f8bdcbaa8b29c81b052/internal/ethapi/api.go#L678

**Comment by web3-developer** [comment]
RPC code in Nimbus is here: https://github.com/status-im/nimbus-eth1/blob/master/nimbus/rpc/p2p.nim

**Comment by web3-developer** [comment]
After reading through the spec and looking at the geth implementation here are a few comments about how the eth_getProof endpoint should be implemented based on my understanding:
- The account and storage proofs contain an array of RLP encoded merkle patrica trie nodes starting from the root node, following the path of the trie key until reaching the leaf node. The leaf node is also included as the final node in the proof.
- When getting an account that doesn't exist in the state we return values set with defaults. Balance and nonce will be zero in this case.
- When returning an account that doesn't exist in the state we also return a proof that prove the absence of the value in the state. In this case the proof will contain all nodes that do exist following the path of the provided key.
- If an account is not a contract account or doesn't exist then the code hash will be equal to the keccak256 hash of an empty string.
- If an account has no storage slots populated than it will have a storageRoot equal to the keccak256 hash of the empty root node.
- If the slots array parameter is empty than we return an empty list for the storageProof.
- If the storage slots are empty in the state but we supply a non empty array of slots as a parameter then we return a storage proof for each non existent slot with the slot value equal to zero. These proofs will prove that the slot doesn't exist in the state.

**Comment by web3-developer** [comment]
It turns out that Geth doesn't completely follow the EIP spec and in the case when no code or storage exists it returns a zeroed value instead of the empty hash. It looks like Besu does follow the spec and returns the hash of the empty string 
if no code exists and the hash of the empty RLP encoded node if no storage exists. I've opted to implement it according to the spec in the same way as Besu because our existing db code already works this way.

**Comment by web3-developer** [comment]
I couldn't find an existing trie.getBranch proc to use for getting the MptProof while using the new CoreDbRef abstractions. The HexaryTrie type in the eth/trie library does implement this but I was unable to use it directly because the proc only supports the HexaryTrie type and not the CoreDbRef types. As a temporary solution I opted to implement a version of the getBranch proc on the CoreDbPhkRef type because its not overly complex. In the future we can refactor this out to use a similar proc but implemented inside the db layer directly.

**Comment by web3-developer** [comment]
The changes for this task have been merged in this PR: https://github.com/status-im/nimbus-eth1/pull/1960
