### ISSUE TITLE
Make Portal state-interop hive tests pass for Fluffy

### ISSUE THREAD

**Issue by kdeme** [status-im/nimbus-eth1#2287]
The `state-interop`  test suite on hive fails for a lot of tests for Fluffy.

See also https://portal-hive-experimental.ethdevops.io/ (e.g. https://portal-hive-experimental.ethdevops.io/suite.html?suiteid=1717426303-49120e0e56335ef3ddcccf85635f70ad.json&suitename=state-interop).

Note that the production hive (https://portal-hive.ethdevops.io/) does not show these tests for Fluffy, as only clients that pass ~100% will be added there in the future.

I've ran them locally with only fluffy as client and they also fail:

```
...
INFO[06-03|20:43:58] simulation portal/state finished         suites=2 tests=47 failed=29
29 tests failed
```

First step would be to get that working, can be ran by doing:
```
git clone https://github.com/ethereum/hive
cd ./hive
go build .

./hive --sim state --client fluffy 
```

**Comment by kdeme** [comment]
cc @web3-developer

**Comment by web3-developer** [comment]
> cc @web3-developer

Thanks @kdeme . I'm looking into it.

**Comment by web3-developer** [comment]
@kdeme  It looks like Fluffy is failing because it is trying to look up the block header in order to get the stateroot required for validation. The Hive state tests don't setup history network data so there is no way for Fluffy to get this data.

It turns out that Trin doesn't yet validate the offered state content against the state root so that is why the tests are passing for them. 

I'm planning to update Fluffy to support disabling the state root validation for the hive tests.

**Comment by web3-developer** [comment]
This PR should fix all the broken hive portal state tests: https://github.com/status-im/nimbus-eth1/pull/2333

**Comment by web3-developer** [comment]
I've also created a PR to update the Fluffy startup options in the Portal hive tests, see here: https://github.com/ethereum/hive/pull/1118
