### ISSUE TITLE
Put block header and block body together in one object

### ISSUE THREAD

**Issue by jangko** [status-im/nimbus-eth1#593]
https://github.com/status-im/nimbus-eth1/blob/e76e0144d07d81b7faed65b674a8bedc932f9bf6/nimbus/p2p/chain.nim#L128

One of the most annoying method appears in both nimbus-eth1 and [nim-eth](https://github.com/status-im/nim-eth/blob/0f3bb6167816b2b16cb0a917ac913d998801bee3/eth/common/eth_types.nim#L429)  is `persistBlocks`. It require block header and block body separated in two object.

The reason why it need to be in one object:
- all test data from EF test suite encode block in one RLP blob, no header and body separation.
- the `--import` command line options required by hive also provide block header and body in one RLP blob.
- graphql test suite reveals this separation become annoyance because we need to repeatedly separate header and body when doing block validation while it is obvious the more natural thing to do is put them in one object.

Currently what we have is:
```Nim
type
  BlockHeader* = object
    parentHash*:    Hash256
    ommersHash*:    Hash256
    coinbase*:      EthAddress
    ...

  BlockBody* = object
    transactions*:  seq[Transaction]
    uncles*:        seq[BlockHeader]
```

The new object will be like this:
```Nim
type
  EthBlock* = object
     header*: BlockHeader
     transactions*:  seq[Transaction]
     uncles*:        seq[BlockHeader]
```

Although the `eth/xx` network protocol might not request or send a block in one message, we can assembly the pieces when they arrived. why assemble it into headers and bodies while we can assemble them into blocks.

**Comment by jlokier** [comment]
We won't be fetching block headers and block bodies exactly synchronised.  In some cases we only want the header in memory without even fetching the body.  Perhaps also in storage.  So there will necessarily be block headers that don't have bodies.

Provided you can easily lookup the body given a header (or get the answer "we don't have the body"), why is having two objects annoying?  Isn't it just like having an object with a pointer to another object?

**Comment by jlokier** [comment]
The definitions of `BlockHeader` and `BlockBody` are just a deserialised version of the RLP, "plain old data" (POD). They aren't really for using as a data structure, for traversals, indexing, attached run-time state etc. Same is true of `Transaction`, etc.

I think that's the source of annoyance. Same thing affects other areas, especially the sync and storage processes.

Real data structures are needed in other areas too in `nimbus-eth1`. An `EthBlock` object, that contains a reference to `BlockBody` (or a method for that) as well as `BlockHeader` would be fine., if that helps you avoid keeping track of both thingsas separate refs all the time, or doing block-number/hash lookups all the time.

Just keep in mind, some `EthBlock` that are in memory won't always have an attached `BlockBody` because the body either has not been fetched (and might not be), or it hasn't been read from the database (which is a heavy operation when the database is busy).

**Comment by jangko** [comment]
this issue posing no problem anymore.
